# Generated by Django 4.1.1 on 2022-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
